FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY --chmod=644 requirements.txt .
# --require-hashes: the image is built by a *remote* daemon from a context
# streamed over SSH, with no registry and no lockfile on the server. Pinned
# versions make two builds install the same version numbers; the hashes make
# them install the same bytes. requirements.txt is generated by pip-compile and
# lists every transitive dependency, which is what the flag requires.
RUN pip install --no-cache-dir --require-hashes -r requirements.txt

COPY --chmod=644 server.py .

RUN useradd --system --uid 10001 --no-create-home mcp
USER 10001

ENV MCP_TRANSPORT=streamable-http \
    MCP_HOST=0.0.0.0 \
    MCP_PORT=8000 \
    MCP_PATH=/mcp

EXPOSE 8000

# Probes the same endpoint deploy.sh polls, so `restart: always` also recovers a
# server that is up but no longer answering — not just one whose process exited.
# Uses python rather than curl/wget: the slim image ships neither, and urlopen
# raises on a non-2xx status, which is exactly the exit code a probe needs.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python -c "import os,urllib.request; urllib.request.urlopen('http://127.0.0.1:' + os.environ.get('MCP_PORT', '8000') + '/healthz', timeout=3)"

CMD ["python", "server.py"]
